// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/cursos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCursoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCursoRequest) Reset() {
	*x = GetCursoRequest{}
	mi := &file_proto_cursos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCursoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCursoRequest) ProtoMessage() {}

func (x *GetCursoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cursos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCursoRequest.ProtoReflect.Descriptor instead.
func (*GetCursoRequest) Descriptor() ([]byte, []int) {
	return file_proto_cursos_proto_rawDescGZIP(), []int{0}
}

func (x *GetCursoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CursoAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CursoId       int32                  `protobuf:"varint,2,opt,name=cursoId,proto3" json:"cursoId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursoAccessRequest) Reset() {
	*x = CursoAccessRequest{}
	mi := &file_proto_cursos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursoAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursoAccessRequest) ProtoMessage() {}

func (x *CursoAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cursos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursoAccessRequest.ProtoReflect.Descriptor instead.
func (*CursoAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_cursos_proto_rawDescGZIP(), []int{1}
}

func (x *CursoAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CursoAccessRequest) GetCursoId() int32 {
	if x != nil {
		return x.CursoId
	}
	return 0
}

type CursoAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursoAccessResponse) Reset() {
	*x = CursoAccessResponse{}
	mi := &file_proto_cursos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursoAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursoAccessResponse) ProtoMessage() {}

func (x *CursoAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cursos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursoAccessResponse.ProtoReflect.Descriptor instead.
func (*CursoAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_cursos_proto_rawDescGZIP(), []int{2}
}

func (x *CursoAccessResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetCursoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Video         string                 `protobuf:"bytes,4,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCursoResponse) Reset() {
	*x = GetCursoResponse{}
	mi := &file_proto_cursos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCursoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCursoResponse) ProtoMessage() {}

func (x *GetCursoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cursos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCursoResponse.ProtoReflect.Descriptor instead.
func (*GetCursoResponse) Descriptor() ([]byte, []int) {
	return file_proto_cursos_proto_rawDescGZIP(), []int{3}
}

func (x *GetCursoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCursoResponse) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *GetCursoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetCursoResponse) GetVideo() string {
	if x != nil {
		return x.Video
	}
	return ""
}

type HiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HiRequest) Reset() {
	*x = HiRequest{}
	mi := &file_proto_cursos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiRequest) ProtoMessage() {}

func (x *HiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cursos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiRequest.ProtoReflect.Descriptor instead.
func (*HiRequest) Descriptor() ([]byte, []int) {
	return file_proto_cursos_proto_rawDescGZIP(), []int{4}
}

func (x *HiRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HiResponse) Reset() {
	*x = HiResponse{}
	mi := &file_proto_cursos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiResponse) ProtoMessage() {}

func (x *HiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cursos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiResponse.ProtoReflect.Descriptor instead.
func (*HiResponse) Descriptor() ([]byte, []int) {
	return file_proto_cursos_proto_rawDescGZIP(), []int{5}
}

func (x *HiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_cursos_proto protoreflect.FileDescriptor

const file_proto_cursos_proto_rawDesc = "" +
	"\n" +
	"\x12proto/cursos.proto\x12\x06cursos\"!\n" +
	"\x0fGetCursoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"F\n" +
	"\x12CursoAccessRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acursoId\x18\x02 \x01(\x05R\acursoId\"%\n" +
	"\x13CursoAccessResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"h\n" +
	"\x10GetCursoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05video\x18\x04 \x01(\tR\x05video\"\x1f\n" +
	"\tHiRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HiResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xd3\x01\n" +
	"\x12CursosProtoService\x12A\n" +
	"\fGetCursoByID\x12\x17.cursos.GetCursoRequest\x1a\x18.cursos.GetCursoResponse\x12J\n" +
	"\x0fCheckUserAccess\x12\x1a.cursos.CursoAccessRequest\x1a\x1b.cursos.CursoAccessResponse\x12.\n" +
	"\x05SayHi\x12\x11.cursos.HiRequest\x1a\x12.cursos.HiResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_cursos_proto_rawDescOnce sync.Once
	file_proto_cursos_proto_rawDescData []byte
)

func file_proto_cursos_proto_rawDescGZIP() []byte {
	file_proto_cursos_proto_rawDescOnce.Do(func() {
		file_proto_cursos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cursos_proto_rawDesc), len(file_proto_cursos_proto_rawDesc)))
	})
	return file_proto_cursos_proto_rawDescData
}

var file_proto_cursos_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_cursos_proto_goTypes = []any{
	(*GetCursoRequest)(nil),     // 0: cursos.GetCursoRequest
	(*CursoAccessRequest)(nil),  // 1: cursos.CursoAccessRequest
	(*CursoAccessResponse)(nil), // 2: cursos.CursoAccessResponse
	(*GetCursoResponse)(nil),    // 3: cursos.GetCursoResponse
	(*HiRequest)(nil),           // 4: cursos.HiRequest
	(*HiResponse)(nil),          // 5: cursos.HiResponse
}
var file_proto_cursos_proto_depIdxs = []int32{
	0, // 0: cursos.CursosProtoService.GetCursoByID:input_type -> cursos.GetCursoRequest
	1, // 1: cursos.CursosProtoService.CheckUserAccess:input_type -> cursos.CursoAccessRequest
	4, // 2: cursos.CursosProtoService.SayHi:input_type -> cursos.HiRequest
	3, // 3: cursos.CursosProtoService.GetCursoByID:output_type -> cursos.GetCursoResponse
	2, // 4: cursos.CursosProtoService.CheckUserAccess:output_type -> cursos.CursoAccessResponse
	5, // 5: cursos.CursosProtoService.SayHi:output_type -> cursos.HiResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cursos_proto_init() }
func file_proto_cursos_proto_init() {
	if File_proto_cursos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cursos_proto_rawDesc), len(file_proto_cursos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cursos_proto_goTypes,
		DependencyIndexes: file_proto_cursos_proto_depIdxs,
		MessageInfos:      file_proto_cursos_proto_msgTypes,
	}.Build()
	File_proto_cursos_proto = out.File
	file_proto_cursos_proto_goTypes = nil
	file_proto_cursos_proto_depIdxs = nil
}
